export const ARTICLES_DATA = [
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "ACIDE PHOSPHORIQUE" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "AMMONITRATE" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "NITRATE DE POTASSE" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "ACIDE NITRIQUE" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "NITRATE DE CALCIUM" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "FER JISAQUEL" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "MAP" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "UREE 46%" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "TRUST MIXTE" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "ACIDE SULFURIQUE" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "MGO" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "TRUST MAX FULL" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "AG3" },
  { famille: "ACHAT", categorie: "BIOSTIMULANT", sous_categorie: "ENRACINNEUR", article: "GZ" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ENGRAIS", article: "SULFATE DE CUIVRE" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "CORRECTEUR PH", article: "TECH-PH" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ETALONNAGE", article: "SOLUTION D'ETALONNAGE PH" },
  { famille: "ACHAT", categorie: "ENGRAIS", sous_categorie: "ETALONNAGE", article: "SOLUTION D'ETALONNAGE EC" },
  { famille: "ACHAT", categorie: "BIOSTIMULANT", sous_categorie: "ENGRAIS FOLIAIRE", article: "ECOVIGOR" },
  { famille: "ACHAT", categorie: "BIOSTIMULANT", sous_categorie: "ENGRAIS FOLIAIRE", article: "BIOMAX" },
  { famille: "ACHAT", categorie: "PHYTOSANITAIRE", sous_categorie: "FONGICIDE", article: "CUIVRE HYDROXYDE" },
  { famille: "ACHAT", categorie: "PHYTOSANITAIRE", sous_categorie: "FONGICIDE", article: "MANCOZEBE" },
  { famille: "ACHAT", categorie: "PHYTOSANITAIRE", sous_categorie: "INSECTICIDE", article: "ABAMECTINE" },
  { famille: "ACHAT", categorie: "PHYTOSANITAIRE", sous_categorie: "INSECTICIDE", article: "SPINOSAD" },
  { famille: "ACHAT", categorie: "PHYTOSANITAIRE", sous_categorie: "HERBICIDE", article: "GLYPHOSATE" },
  { famille: "ACHAT", categorie: "SUBSTRAT", sous_categorie: "SUBSTRAT", article: "TOURBE" },
  { famille: "ACHAT", categorie: "SUBSTRAT", sous_categorie: "SUBSTRAT", article: "PERLITE" },
  { famille: "ACHAT", categorie: "SUBSTRAT", sous_categorie: "SUBSTRAT", article: "COCOS" },
  { famille: "ACHAT", categorie: "EMBALLAGE", sous_categorie: "EMBALLAGE", article: "BARQUETTES 250G" },
  { famille: "ACHAT", categorie: "EMBALLAGE", sous_categorie: "EMBALLAGE", article: "BARQUETTES 500G" },
  { famille: "ACHAT", categorie: "EMBALLAGE", sous_categorie: "EMBALLAGE", article: "CARTONS EXPORT" },
  { famille: "ACHAT", categorie: "ENERGIE", sous_categorie: "ENERGIE", article: "FIOUL" },
  { famille: "ACHAT", categorie: "ENERGIE", sous_categorie: "ENERGIE", article: "GAZ PROPANE" },
  { famille: "ACHAT", categorie: "ENERGIE", sous_categorie: "ENERGIE", article: "ELECTRICITE" },
];

export const UNITES = [
  "KG",
  "T (Tonne)",
  "L (Litre)",
  "M³",
  "Pièce",
  "Sac",
  "Boîte",
  "Palette",
  "Bidon",
  "Carton",
  "Unité",
];
